export const catsData = [
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "angry.jpeg",
        alt: "Moody picture",
    },
    {
        emotionTags: ["confused", "sad"],
        isGif: false,
        image: "confused.jpeg",
        alt: "confused",
    },
    {
        emotionTags: ["happy", "relaxed"],
        isGif: false,
        image: "happy.jpeg",
        alt: "happy",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "hungry.jpeg",
        alt: "hungry",
    },
    {
        emotionTags: ["insomniac"],
        isGif: false,
        image: "insomnia.jpeg",
        alt: "insomniac",
    },
    {
        emotionTags: ["relaxed"],
        isGif: false,
        image: "lazy.jpeg",
        alt: "lazy",
    },
    {
        emotionTags: ["scared"],
        isGif: false,
        image: "nervous.jpeg",
        alt: "nervous",
    },
    {
        emotionTags: ["sad", "moody"],
        isGif: false,
        image: "sad1.jpeg",
        alt: "sad",
    },
    {
        emotionTags: ["angry"],
        isGif: true,
        image: "angry.gif",
        alt: "angry",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "confused.gif",
        alt: "confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "dominant.gif",
        alt: "dominant",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "happy.gif",
        alt: "happy",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "hungry.gif",
        alt: "hungry",
    },
    {
        emotionTags: ["insomniac"],
        isGif: true,
        image: "insomniac.gif",
        alt: "insomniac",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "moody.gif",
        alt: "Moody",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "relaxed.gif",
        alt: "relaxed",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "sad.gif",
        alt: "Sad",
    },
]